spring.application.name=student-verification-app
server.port=8080


spring.datasource.url=jdbc:mysql://localhost:3306/studentdb
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Mail settings. For Gmail use an App Password, not your normal password.
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=amit421.tiwari@gmail.com
spring.mail.password=qpbddplfurrzlxgn

spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Twilio SMS settings
app.twilio.account-sid=AC82030a81d12e57aa972b2352b53a35d9
app.twilio.auth-token=6048f290001e0aa80520da843e5cc190
app.twilio.from-phone=+13367371375

# Cloudinary settings
cloudinary.cloud-name=dtrrkiv9u
cloudinary.api-key=232171276438611
cloudinary.api-secret=TWcdYPvwiT8Ylt6O9yJxLhBBilc

# JWT settings. Use at least 32 chars for HS256.
app.jwt.secret=change-this-secret-key-minimum-32-characters
app.jwt.expiration-ms=86400000

# OTP settings
app.otp.expiry-minutes=5
