spring.application.name=05_Spring_Hibernate_Employee

spring.datasource.url= jdbc:mysql://localhost:3306/employee_test
spring.datasource.username= springstudent
spring.datasource.password= springstudent

spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true